# Generated by Django 3.1.3 on 2020-11-13 15:15

from django.db import migrations, models
import singers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('group', models.BooleanField(default=False)),
                ('group_name', models.CharField(default=None, max_length=25)),
                ('from_macedonia', models.BooleanField(default=False)),
                ('age', models.IntegerField(validators=[singers.models.validate_age])),
            ],
        ),
    ]
