# Generated by Django 3.1.3 on 2020-11-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='group_name',
            field=models.CharField(max_length=25),
        ),
    ]
