# Generated by Django 3.1.3 on 2020-11-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singers', '0002_auto_20201115_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='group_name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
