# Generated by Django 3.1.3 on 2020-11-16 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singers', '0003_auto_20201115_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
